---
kind: pipeline
name: default

workspace:
    base: /drone
    path: src/bitbucket.org/nectwork/${DRONE_REPO_NAME}/

global:

  # individual per project
  default_step_image: &default_step_image harbor.int.svc.nect.com/nect-ml-images/nectml-tf-official-dev:2.0.0
  default_kubectl_image: &default_kubectl_image harbor.int.svc.nect.com/ci/helm-kubectl:2.11.0-4
  default_deploy_image: &default_deploy_image harbor.int.svc.nect.com/ci/deploy:0.0.10
  default_checkpoint_image: &default_checkpoint_image harbor.int.svc.nect.com/hub.docker.com-proxy/library/alpine

  project_version: &project_version {{ cookiecutter.namespace_name.upper() }}_VERSION
  project_coverage: &project_coverage {{ cookiecutter.namespace_name }}
